spring:
  sleuth:
    sampler:
      # 抽样采集率
      probability: 1
  application:
    name: sleuth-and-zipkin
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
server:
  port: 9090
logging:
  level:
   org:
     springframework:
       cloud:
         openfeign: DEBUG
         sleuth: DEBUG
