spring:
  application:
    name: serviceServer
  freemarker:
    prefer-file-system-access: false
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/,http://localhost:8082/eureka/
  instance:
    hostname: web