spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: gateway
    gateway:
      routes:
        - id: full
          uri: forward:/notFound
          predicates:
            - Path=/**
        - id: index
          uri: http://localhost:9001/index
          predicates:
            - Path=/index
      discovery:
        locator:
          enabled: true
server:
  port: 9021
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    top:
      gabin:
        coupons: DEBUG