spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: gateway
    gateway:
      routes:
        - id: index
          uri: http://localhost:9001/index
          predicates:
            - Path=/index
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 2
                key-resolver: "#{@ipKeyResolver}"
        - id: full
          uri: forward:/notFound
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
server:
  port: 9021
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    top:
      gabin:
        coupons: DEBUG
# 支持熔断
feign:
  hystrix:
    enabled: true