spring:
  application:
    name: consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: consumer
server:
  port: 9001
logging:
  level:
    top:
      gabin:
        coupons: DEBUG
feign:
  hystrix:
    enabled: true